<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DINESH" name="com.testng.dataprovider1" tests="1" failures="0" timestamp="07 Sep 2022 04:54:32 GMT" time="0.025" errors="1">
  <testcase name="m1" time="0.025" classname="com.testng.dataprovider1">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: m1([])
Arguments: [(java.lang.Integer) 0,(java.lang.Integer) 1,(java.lang.String) dinesh,(java.lang.String) porur,(java.lang.String) chennai,(java.lang.String) tamilnadu,(java.lang.String) 1234,(java.lang.Integer) 0,(java.lang.String) 1234567890123456,(java.lang.String) jan,(java.lang.String) 2021,(java.lang.String) greencard,(java.lang.String) 123,(java.lang.Integer) 10,(java.lang.Integer) 10]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: m1([])
Arguments: [(java.lang.Integer) 0,(java.lang.Integer) 1,(java.lang.String) dinesh,(java.lang.String) porur,(java.lang.String) chennai,(java.lang.String) tamilnadu,(java.lang.String) 1234,(java.lang.Integer) 0,(java.lang.String) 1234567890123456,(java.lang.String) jan,(java.lang.String) 2021,(java.lang.String) greencard,(java.lang.String) 123,(java.lang.Integer) 10,(java.lang.Integer) 10]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- m1 -->
</testsuite> <!-- com.testng.dataprovider1 -->
